#include "operations.hpp"

std::map<uint8_t, OperationInfo> operations = {
	{0x00, {0x00, "BRK", AddressingMode::implicit, 7}},
	{0x01, {0x01, "ORA", AddressingMode::indirect_x_read, 6}},
	// {0x02, {&Cpu::stp, AddressingMode::implicit}},
	// {0x03, {&Cpu::nop, AddressingMode::implicit}},
	// {0x04, {&Cpu::nop, AddressingMode::implicit}},
	{0x05, {0x05, "ORA", AddressingMode::zero_page, 3}},
	{0x06, {0x06, "ASL", AddressingMode::zero_page, 5}},
	// {0x07, {&Cpu::nop, AddressingMode::implicit}},
	{0x08, {0x08, "PHP", AddressingMode::implicit, 3}},
	{0x09, {0x09, "ORA", AddressingMode::immediate, 2}},
	{0x0a, {0x0a, "ASL", AddressingMode::accumulator, 2}},
	// {0x0b, {&Cpu::nop, AddressingMode::implicit}},
	// {0x0c, {&Cpu::nop, AddressingMode::implicit}},
	{0x0d, {0x0d, "ORA", AddressingMode::absolute, 4}},
	{0x0e, {0x0e, "ASL", AddressingMode::absolute, 6}},
	// {0x0f, {&Cpu::nop, AddressingMode::implicit}},
	{0x10, {0x10, "BPL", AddressingMode::relative, 2}},
	{0x11, {0x11, "ORA", AddressingMode::indirect_y_read, 5}},
	// {0x12, {&Cpu::stp, AddressingMode::implicit}},
	// {0x13, {&Cpu::nop, AddressingMode::implicit}},
	// {0x14, {&Cpu::nop, AddressingMode::implicit}},
	{0x15, {0x15, "ORA", AddressingMode::zero_page_x_read, 4}},
	{0x16, {0x16, "ASL", AddressingMode::zero_page_x_read, 6}},
	// {0x17, {&Cpu::nop, AddressingMode::implicit}},
	{0x18, {0x18, "CLC", AddressingMode::implicit, 2}},
	{0x19, {0x19, "ORA", AddressingMode::absolute_y_read, 4}},
	// {0x1a, {&Cpu::nop, AddressingMode::implicit}},
	// {0x1b, {&Cpu::nop, AddressingMode::implicit}},
	// {0x1c, {&Cpu::nop, AddressingMode::implicit}},
	{0x1d, {0x1d, "ORA", AddressingMode::absolute_x_read, 4}},
	{0x1e, {0x1e, "ASL", AddressingMode::absolute_x_write, 7}},
	// {0x1f, {&Cpu::nop, AddressingMode::implicit}},
	{0x20, {0x20, "JSR", AddressingMode::absolute, 6}},
	{0x21, {0x21, "AND", AddressingMode::indirect_x_read, 6}},
	// {0x22, {&Cpu::nop, AddressingMode::implicit}},
	// {0x23, {&Cpu::nop, AddressingMode::implicit}},
	{0x24, {0x24, "BIT", AddressingMode::zero_page, 3}},
	{0x25, {0x25, "AND", AddressingMode::zero_page, 3}},
	{0x26, {0x26, "ROL", AddressingMode::zero_page, 5}},
	// {0x27, {&Cpu::nop, AddressingMode::implicit}},
	{0x28, {0x28, "PLP", AddressingMode::implicit, 4}},
	{0x29, {0x29, "AND", AddressingMode::immediate, 2}},
	{0x2a, {0x2a, "ROL", AddressingMode::accumulator, 2}},
	// {0x2b, {&Cpu::nop, AddressingMode::implicit}},
	{0x2c, {0x2c, "BIT", AddressingMode::absolute, 4}},
	{0x2d, {0x2d, "AND", AddressingMode::absolute, 4}},
	{0x2e, {0x2e, "ROL", AddressingMode::absolute, 6}},
	// {0x2f, {&Cpu::nop, AddressingMode::implicit}},
	{0x30, {0x30, "BMI", AddressingMode::relative, 2}},
	{0x31, {0x31, "AND", AddressingMode::indirect_y_read, 5}},
	// {0x32, {&Cpu::nop, AddressingMode::implicit}},
	// {0x33, {&Cpu::nop, AddressingMode::implicit}},
	// {0x34, {&Cpu::nop, AddressingMode::implicit}},
	{0x35, {0x35, "AND", AddressingMode::zero_page_x_read, 4}},
	{0x36, {0x36, "ROL", AddressingMode::zero_page_x_read, 6}},
	// {0x37, {&Cpu::nop, AddressingMode::implicit}},
	{0x38, {0x38, "SEC", AddressingMode::implicit, 2}},
	{0x39, {0x39, "AND", AddressingMode::absolute_y_read, 4}},
	// {0x3a, {&Cpu::nop, AddressingMode::implicit}},
	// {0x3b, {&Cpu::nop, AddressingMode::implicit}},
	// {0x3c, {&Cpu::nop, AddressingMode::implicit}},
	{0x3d, {0x3d, "AND", AddressingMode::absolute_x_read, 4}},
	{0x3e, {0x3e, "ROL", AddressingMode::absolute_x_write, 7}},
	// {0x3f, {&Cpu::nop, AddressingMode::implicit}},
	{0x40, {0x40, "RTI", AddressingMode::implicit, 6}},
	{0x41, {0x41, "EOR", AddressingMode::indirect_x_read, 6}},
	// {0x42, {&Cpu::nop, AddressingMode::implicit}},
	// {0x43, {&Cpu::nop, AddressingMode::implicit}},
	// {0x44, {&Cpu::nop, AddressingMode::implicit}},
	{0x45, {0x45, "EOR", AddressingMode::zero_page, 3}},
	{0x46, {0x46, "LSR", AddressingMode::zero_page, 5}},
	// {0x47, {&Cpu::nop, AddressingMode::implicit}},
	{0x48, {0x48, "PHA", AddressingMode::implicit, 3}},
	{0x49, {0x49, "EOR", AddressingMode::immediate, 2}},
	{0x4a, {0x4a, "LSR", AddressingMode::accumulator, 2}},
	// {0x4b, {&Cpu::nop, AddressingMode::implicit}},
	{0x4c, {0x4c, "JMP", AddressingMode::absolute, 3}},
	{0x4d, {0x4d, "EOR", AddressingMode::absolute, 4}},
	{0x4e, {0x4e, "LSR", AddressingMode::absolute, 6}},
	// {0x4f, {&Cpu::nop, AddressingMode::implicit}},
	{0x50, {0x50, "BVC", AddressingMode::relative, 2}},
	{0x51, {0x51, "EOR", AddressingMode::indirect_y_read, 5}},
	// {0x52, {&Cpu::nop, AddressingMode::implicit}},
	// {0x53, {&Cpu::nop, AddressingMode::implicit}},
	// {0x54, {&Cpu::nop, AddressingMode::implicit}},
	{0x55, {0x55, "EOR", AddressingMode::zero_page_x_read, 4}},
	{0x56, {0x56, "LSR", AddressingMode::zero_page_x_read, 6}},
	// {0x57, {&Cpu::nop, AddressingMode::implicit}},
	{0x58, {0x58, "CLI", AddressingMode::implicit, 2}},
	{0x59, {0x59, "EOR", AddressingMode::absolute_y_read, 4}},
	// {0x5a, {&Cpu::nop, AddressingMode::implicit}},
	// {0x5b, {&Cpu::nop, AddressingMode::implicit}},
	// {0x5c, {&Cpu::nop, AddressingMode::implicit}},
	{0x5d, {0x5d, "EOR", AddressingMode::absolute_x_read, 4}},
	{0x5e, {0x5e, "LSR", AddressingMode::absolute_x_write, 7}},
	// {0x5f, {&Cpu::nop, AddressingMode::implicit}},
	{0x60, {0x60, "RTS", AddressingMode::implicit, 6}},
	{0x61, {0x61, "ADC", AddressingMode::indirect_x_read, 6}},
	// {0x62, {&Cpu::nop, AddressingMode::implicit}},
	// {0x63, {&Cpu::nop, AddressingMode::implicit}},
	// {0x64, {&Cpu::nop, AddressingMode::implicit}},
	{0x65, {0x65, "ADC", AddressingMode::zero_page, 3}},
	{0x66, {0x66, "ROR", AddressingMode::zero_page, 5}},
	// {0x67, {&Cpu::nop, AddressingMode::implicit}},
	{0x68, {0x68, "PLA", AddressingMode::implicit, 4}},
	{0x69, {0x69, "ADC", AddressingMode::immediate, 2}},
	{0x6a, {0x6a, "ROR", AddressingMode::accumulator, 2}},
	// {0x6b, {&Cpu::nop, AddressingMode::implicit}},
	{0x6c, {0x6c, "JMP", AddressingMode::indirect, 5}},
	{0x6d, {0x6d, "ADC", AddressingMode::absolute, 4}},
	{0x6e, {0x6e, "ROR", AddressingMode::absolute, 6}},
	// {0x6f, {&Cpu::nop, AddressingMode::implicit}},
	{0x70, {0x70, "BVS", AddressingMode::relative, 2}},
	{0x71, {0x71, "ADC", AddressingMode::indirect_y_read, 5}},
	// {0x72, {&Cpu::nop, AddressingMode::implicit}},
	// {0x73, {&Cpu::nop, AddressingMode::implicit}},
	// {0x74, {&Cpu::nop, AddressingMode::implicit}},
	{0x75, {0x75, "ADC", AddressingMode::zero_page_x_read, 4}},
	{0x76, {0x76, "ROR", AddressingMode::zero_page_x_read, 6}},
	// {0x77, {&Cpu::nop, AddressingMode::implicit}},
	{0x78, {0x78, "SEI", AddressingMode::implicit, 2}},
	{0x79, {0x79, "ADC", AddressingMode::absolute_y_read, 4}},
	// {0x7a, {&Cpu::nop, AddressingMode::implicit}},
	// {0x7b, {&Cpu::nop, AddressingMode::implicit}},
	// {0x7c, {&Cpu::nop, AddressingMode::implicit}},
	{0x7d, {0x7d, "ADC", AddressingMode::absolute_x_read, 4}},
	{0x7e, {0x7e, "ROR", AddressingMode::absolute_x_write, 7}},
	// {0x7f, {&Cpu::nop, AddressingMode::implicit}},
	// {0x80, {&Cpu::nop, AddressingMode::implicit}},
	{0x81, {0x81, "STA", AddressingMode::indirect_x_write, 6}},
	// {0x82, {&Cpu::nop, AddressingMode::implicit}},
	// {0x83, {&Cpu::nop, AddressingMode::implicit}},
	{0x84, {0x84, "STY", AddressingMode::zero_page, 3}},
	{0x85, {0x85, "STA", AddressingMode::zero_page, 3}},
	{0x86, {0x86, "STX", AddressingMode::zero_page, 3}},
	// {0x87, {&Cpu::nop, AddressingMode::implicit}},
	{0x88, {0x88, "DEY", AddressingMode::implicit, 2}},
	// {0x89, {&Cpu::nop, AddressingMode::implicit}},
	{0x8a, {0x8a, "TXA", AddressingMode::implicit, 2}},
	// {0x8b, {&Cpu::nop, AddressingMode::implicit}},
	{0x8c, {0x8c, "STY", AddressingMode::absolute, 4}},
	{0x8d, {0x8d, "STA", AddressingMode::absolute, 4}},
	{0x8e, {0x8e, "STX", AddressingMode::absolute, 4}},
	// {0x8f, {&Cpu::nop, AddressingMode::implicit}},
	{0x90, {0x90, "BCC", AddressingMode::relative, 2}},
	{0x91, {0x91, "STA", AddressingMode::indirect_y_write, 6}},
	// {0x92, {&Cpu::nop, AddressingMode::implicit}},
	// {0x93, {&Cpu::nop, AddressingMode::implicit}},
	{0x94, {0x94, "STY", AddressingMode::zero_page_x_write, 4}},
	{0x95, {0x95, "STA", AddressingMode::zero_page_x_write, 4}},
	{0x96, {0x96, "STX", AddressingMode::zero_page_y_write, 4}},
	// {0x97, {&Cpu::nop, AddressingMode::implicit}},
	{0x98, {0x98, "TYA", AddressingMode::implicit, 2}},
	{0x99, {0x99, "STA", AddressingMode::absolute_y_write, 5}},
	{0x9a, {0x9a, "TXS", AddressingMode::implicit, 2}},
	// {0x9b, {&Cpu::nop, AddressingMode::implicit}},
	// {0x9c, {&Cpu::nop, AddressingMode::implicit}},
	{0x9d, {0x9d, "STA", AddressingMode::absolute_x_write, 5}},
	// {0x9e, {&Cpu::nop, AddressingMode::implicit}},
	// {0x9f, {&Cpu::nop, AddressingMode::implicit}},
	{0xa0, {0xa0, "LDY", AddressingMode::immediate, 2}},
	{0xa1, {0xa1, "LDA", AddressingMode::indirect_x_read, 6}},
	{0xa2, {0xa2, "LDX", AddressingMode::immediate, 2}},
	// {0xa3, {&Cpu::nop, AddressingMode::implicit}},
	{0xa4, {0xa4, "LDY", AddressingMode::zero_page, 3}},
	{0xa5, {0xa5, "LDA", AddressingMode::zero_page, 3}},
	{0xa6, {0xa6, "LDX", AddressingMode::zero_page, 3}},
	// {0xa7, {&Cpu::nop, AddressingMode::implicit}},
	{0xa8, {0xa8, "TAY", AddressingMode::implicit, 2}},
	{0xa9, {0xa9, "LDA", AddressingMode::immediate, 2}},
	{0xaa, {0xaa, "TAX", AddressingMode::implicit, 2}},
	// {0xab, {&Cpu::nop, AddressingMode::implicit}},
	{0xac, {0xac, "LDY", AddressingMode::absolute, 4}},
	{0xad, {0xad, "LDA", AddressingMode::absolute, 4}},
	{0xae, {0xae, "LDX", AddressingMode::absolute, 4}},
	// {0xaf, {&Cpu::nop, AddressingMode::implicit}},
	{0xb0, {0xb0, "BCS", AddressingMode::relative, 2}},
	{0xb1, {0xb1, "LDA", AddressingMode::indirect_y_read, 5}},
	// {0xb2, {&Cpu::nop, AddressingMode::implicit}},
	// {0xb3, {&Cpu::nop, AddressingMode::implicit}},
	{0xb4, {0xb4, "LDY", AddressingMode::zero_page_x_read, 4}},
	{0xb5, {0xb5, "LDA", AddressingMode::zero_page_x_read, 4}},
	{0xb6, {0xb6, "LDX", AddressingMode::zero_page_y_read, 4}},
	// {0xb7, {&Cpu::nop, AddressingMode::implicit}},
	{0xb8, {0xb8, "CLV", AddressingMode::implicit, 2}},
	{0xb9, {0xb9, "LDA", AddressingMode::absolute_y_read, 4}},
	{0xba, {0xba, "TSX", AddressingMode::implicit, 2}},
	// {0xbb, {&Cpu::nop, AddressingMode::implicit}},
	{0xbc, {0xbc, "LDY", AddressingMode::absolute_x_read, 4}},
	{0xbd, {0xbd, "LDA", AddressingMode::absolute_x_read, 4}},
	{0xbe, {0xbe, "LDX", AddressingMode::absolute_y_read, 4}},
	// {0xbf, {&Cpu::nop, AddressingMode::implicit}},
	{0xc0, {0xc0, "CPY", AddressingMode::immediate, 2}},
	{0xc1, {0xc1, "CMP", AddressingMode::indirect_x_read, 6}},
	// {0xc2, {&Cpu::nop, AddressingMode::implicit}},
	// {0xc3, {&Cpu::nop, AddressingMode::implicit}},
	{0xc4, {0xc4, "CPY", AddressingMode::zero_page, 3}},
	{0xc5, {0xc5, "CMP", AddressingMode::zero_page, 3}},
	{0xc6, {0xc6, "DEC", AddressingMode::zero_page, 5}},
	// {0xc7, {&Cpu::nop, AddressingMode::implicit}},
	{0xc8, {0xc8, "INY", AddressingMode::implicit, 2}},
	{0xc9, {0xc9, "CMP", AddressingMode::immediate, 2}},
	{0xca, {0xca, "DEX", AddressingMode::implicit, 2}},
	// {0xcb, {&Cpu::nop, AddressingMode::implicit}},
	{0xcc, {0xcc, "CPY", AddressingMode::absolute, 4}},
	{0xcd, {0xcd, "CMP", AddressingMode::absolute, 4}},
	{0xce, {0xce, "DEC", AddressingMode::absolute, 6}},
	// {0xcf, {&Cpu::nop, AddressingMode::implicit}},
	{0xd0, {0xd0, "BNE", AddressingMode::relative, 2}},
	{0xd1, {0xd1, "CMP", AddressingMode::indirect_y_read, 5}},
	// {0xd2, {&Cpu::nop, AddressingMode::implicit}},
	// {0xd3, {&Cpu::nop, AddressingMode::implicit}},
	// {0xd4, {&Cpu::nop, AddressingMode::implicit}},
	{0xd5, {0xd5, "CMP", AddressingMode::zero_page_x_read, 4}},
	{0xd6, {0xd6, "DEC", AddressingMode::zero_page_x_read, 6}},
	// {0xd7, {&Cpu::nop, AddressingMode::implicit}},
	{0xd8, {0xd8, "CLD", AddressingMode::implicit, 2}},
	{0xd9, {0xd9, "CMP", AddressingMode::absolute_y_read, 4}},
	// {0xda, {&Cpu::nop, AddressingMode::implicit}},
	// {0xdb, {&Cpu::nop, AddressingMode::implicit}},
	// {0xdc, {&Cpu::nop, AddressingMode::implicit}},
	{0xdd, {0xdd, "CMP", AddressingMode::absolute_x_read, 4}},
	{0xde, {0xde, "DEC", AddressingMode::absolute_x_write, 7}},
	// {0xdf, {&Cpu::nop, AddressingMode::implicit}},
	{0xe0, {0xe0, "CPX", AddressingMode::immediate, 2}},
	{0xe1, {0xe1, "SBC", AddressingMode::indirect_x_read, 6}},
	// {0xe2, {&Cpu::nop, AddressingMode::implicit}},
	// {0xe3, {&Cpu::nop, AddressingMode::implicit}},
	{0xe4, {0xe4, "CPX", AddressingMode::zero_page, 3}},
	{0xe5, {0xe5, "SBC", AddressingMode::zero_page, 3}},
	{0xe6, {0xe6, "INC", AddressingMode::zero_page, 5}},
	// {0xe7, {&Cpu::nop, AddressingMode::implicit}},
	{0xe8, {0xe8, "INX", AddressingMode::implicit, 2}},
	{0xe9, {0xe9, "SBC", AddressingMode::immediate, 2}},
	{0xea, {0xea, "NOP", AddressingMode::implicit, 2}},
	// {0xeb, {&Cpu::nop, AddressingMode::implicit}},
	{0xec, {0xec, "CPX", AddressingMode::absolute, 4}},
	{0xed, {0xed, "SBC", AddressingMode::absolute, 4}},
	{0xee, {0xee, "INC", AddressingMode::absolute, 6}},
	// {0xef, {&Cpu::nop, AddressingMode::implicit}},
	{0xf0, {0xf0, "BEQ", AddressingMode::relative, 2}},
	{0xf1, {0xf1, "SBC", AddressingMode::indirect_y_read, 5}},
	// {0xf2, {&Cpu::nop, AddressingMode::implicit}},
	// {0xf3, {&Cpu::nop, AddressingMode::implicit}},
	// {0xf4, {&Cpu::nop, AddressingMode::implicit}},
	{0xf5, {0xf5, "SBC", AddressingMode::zero_page_x_read, 4}},
	{0xf6, {0xf6, "INC", AddressingMode::zero_page_x_write, 6}},
	// {0xf7, {&Cpu::nop, AddressingMode::implicit}},
	{0xf8, {0xf8, "SED", AddressingMode::implicit, 2}},
	{0xf9, {0xf9, "SBC", AddressingMode::absolute_y_read, 4}},
	// {0xfa, {&Cpu::nop, AddressingMode::implicit}},
	// {0xfb, {&Cpu::nop, AddressingMode::implicit}},
	// {0xfc, {&Cpu::nop, AddressingMode::implicit}},
	{0xfd, {0xfd, "SBC", AddressingMode::absolute_x_read, 4}},
	{0xfe, {0xfe, "INC", AddressingMode::absolute_x_write, 7}},
	// {0xff, {&Cpu::nop, AddressingMode::implicit}},
};
